name: neutron_cli
description: CLI tool for NeutronX - Flutter-first Dart backend framework
version: 0.1.0
homepage: https://github.com/neutronx-labs/neutronx.git

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.7.0
  neutronx: ^0.1.0
  path: ^1.9.1
  recase: ^4.1.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.28.0

executables:
  neutron: neutron
