name: tmp_project
description: A NeutronX backend application
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  neutronx:
    path: /Users/nikhil/NeutronX/packages/neutronx

dev_dependencies:
  lints: ^6.0.0
  test: ^1.28.0
